application: bank-of-mom
version: auto
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/spi/.*
  script: server.api.application
  secure: always
- url: /bower_components
  static_dir: client/app/bower_components
  secure: always
- url: /css
  static_dir: client/app/css
  secure: always
- url: /img
  static_dir: client/app/img
  secure: always
- url: /js
  static_dir: client/app/build/js
  secure: always
- url: /partials
  static_dir: client/app/partials
  secure: always
- url: /.*
  script: server.main.application
  secure: always

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
- name: webapp2
  version: latest
- name: jinja2
  version: latest

builtins:
- appstats: on

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^client/app/bower_components/.*
- ^client/node_modules/.*
- ^client/test/.*
