application: bank-of-mom
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/spi/.*
  script: server.api.application
  secure: always
- url: /bower_components
  static_dir: client/app/bower_components
  secure: always
- url: /css
  static_dir: client/app/css
  secure: always
- url: /img
  static_dir: client/app/img
  secure: always
- url: /js
  static_dir: client/app/js
  secure: always
- url: /partials
  static_dir: client/app/partials
  secure: always
- url: /
  static_files: client/app/index.html
  upload: client/app/index\.html
  secure: always

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0

builtins:
- appstats: on

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^client/app/bower_components/.*
- ^client/node_modules/.*
- ^client/test/.*
